- name: Setup up Delfi-PQ software
  hosts: all
  vars:
    pq_workspace: "~/test_repo/"
    repo_user:  "nchronas"
  tasks:
  - name: clone subsystem repos
    include_tasks: subsystems_clone.yml
    with_items:
      - ADB
      - EPS
      - OBC
      - ADCS
      - COMMS
      - MPP
      - PQ9_bus
    loop_control:
      loop_var: repo_clone
  - name: clone sensor repos
    include_tasks: sensors_clone.yml
    with_items:
      - INA226
      - TMP100
      - MB85RS256A
      - LTC2942
      - AD5235
    loop_control:
      loop_var: repo_clone
