- name: Setup up Delfi-PQ software
  hosts: all
  vars:
    pq_workspace: "~/delfi_PQ/"
    repo_user:  "nchronas"
    subsystems:
      - ADB
      - EPS
      - OBC
      - ADCS
      - COMMS
      - MPP
    sensors:
      - INA226
      - TMP100
      - MB85RS256A
      - LTC2942
      - AD5235
    sensor_configuration:
      - sensor: INA226
        subsystem:
          - EPS
          - OBC
          - ADCS
          - MPP
          - ADB
      - sensor: TMP100
        subsystem:
          - EPS
          - OBC
          - ADCS
          - MPP
          - ADB
      - sensor: MB85RS256A
        subsystem:
          - OBC
          - ADCS
          - MPP
      - sensor: LTC2942
        subsystem:
          - EPS
      - sensor: AD5235
        subsystem:
          - MPP
  tasks:
  - name: clone main repo
    include_tasks: subsystems_clone.yml
    with_items:
      - PQ9_bus
    loop_control:
      loop_var: repo_clone

  - name: clone subsystem repos
    include_tasks: subsystems_clone.yml
    with_items: '{{ subsystems }}'
    loop_control:
      loop_var: repo_clone

  - name: clone sensor repos
    include_tasks: sensors_clone.yml
    with_items: '{{ sensors }}'
    loop_control:
      loop_var: repo_clone

  - name: link subsystem files
    include_tasks: subsystems_link.yml
    with_items: '{{ subsystems }}'
    loop_control:
      loop_var: subsystem

  - name: link sensors files
    include_tasks: sensors_link.yml
    with_items: '{{ sensor_configuration }}'
    loop_control:
      loop_var: config
